eGov/blog/urls.py
from django.conf.urls import url, include
from . import views
from django.views.generic import ListView, DetailView
from blog.models import Posts

urlpatterns = [ 
                url(r'^noticias/$', views.Noticias, name='noticias'),

                url(r'^insertPost/$', views.insertPost, name='insertPost'),

                url(r'^insertProject/$', views.insertProject, name='insertProject'),

                url(r'^updateUser/$', views.updateUser, name='updateUser'),

                url(r'^proyectos/$', views.Proyectos, name='proyectos'),

                url(r'^noticias/(?P<id>[0-9]+)$',views.NoticiasDetail, name='postNoticias'),

            

                url(r'^noticias/aceptarNoticia/(?P<id>[0-9]+)$',views.aceptarNoticia, name='aceptarNoticia'),

                url(r'^noticias/rechazarNoticia/(?P<id>[0-9]+)$',views.rechazarNoticia, name='rechazarNoticia'),

                url(r'^proyectos/addYes/(?P<id>[0-9]+)/$', views.ProyectoAddYes, name='ProyectoAddYes'),

                url(r'^proyectos/addNo/(?P<id>[0-9]+)/$', views.ProyectoAddNo, name='ProyectoAddNo'),

                url(r'^proyectos/addUnknown/(?P<id>[0-9]+)/$', views.ProyectoAddUnknown, name='ProyectoAddUnknown'),

                url(r'^noticias/deletePost/(?P<id>[0-9]+)$',views.deletePost, name='deletePost'),

                url(r'^proyectos/(?P<id>[0-9]+)/$', views.ProyectosDetail, name='postProyectos'),
                
                url(r'^proyectos/new/$', views.newProject, name='newProject'),

                url(r'^noticias/new/$', views.newNoticia, name='newNoticia'),

                url(r'^noticias/editar/(?P<id>[0-9]+)$', views.editarNoticia, name='editarNoticia'),

                url(r'^noticias/editarEsp/(?P<id>[0-9]+)$', views.editarNoticiaEsp, name='editarNoticiaEsp'),

                url(r'^perfil/$', views.Profile, name='Perfil'),

                url(r'^comentario/(?P<id>[0-9]+)$',views.insertComment, name='insertComment'),
				
				url(r'^comentarioProyecto/(?P<id>[0-9]+)$',views.insertCommentProject, name='insertCommentProject'),


                
            ]

eGov/eGov/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace="home")),
    url(r'^personal/', include('personal.urls', namespace="personal")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^blogClient/', include('blogClient.urls', namespace="blogClient")),
    
]

eGov/personal/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^contacto/$', views.contact, name='contact'),
    url(r'^nosotros/$', views.nosotros, name='nosotros'),
    url(r'^contacto/enviarCorreo/$', views.enviarCorreo, name='enviarCorreo'),
    ]

eGov/personal/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class BlogComment(models.Model):
    user = models.CharField(max_length=140)
    date = models.DateTimeField()
    description = models.TextField()
    post = models.ForeignKey('BlogPost', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'blog_comment'


class BlogPost(models.Model):
    title = models.CharField(max_length=140)
    description = models.TextField()
    content = models.TextField()
    date = models.DateTimeField()
    user = models.CharField(max_length=140)
    userp = models.ForeignKey('BlogUser', models.DO_NOTHING, db_column='userP_id', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'blog_post'


class BlogUser(models.Model):
    name = models.CharField(max_length=140)
    lastname = models.CharField(db_column='lastName', max_length=140)  # Field name made lowercase.
    email = models.CharField(max_length=140)
    password = models.CharField(max_length=140)

    class Meta:
        managed = False
        db_table = 'blog_user'


class Comments(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=500, blank=True, null=True)  # Field name made lowercase.
    date = models.DateField(db_column='Date', blank=True, null=True)  # Field name made lowercase.
    fk_user = models.ForeignKey('Users', models.DO_NOTHING, db_column='FK_User', blank=True, null=True)  # Field name made lowercase.
    fk_post = models.ForeignKey('Posts', models.DO_NOTHING, db_column='FK_Post', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'comments'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Images(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    path = models.CharField(db_column='Path', max_length=100, blank=True, null=True)  # Field name made lowercase.
    fk_post = models.ForeignKey('Posts', models.DO_NOTHING, db_column='FK_Post', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'images'


class Lawprojects(models.Model):
    fk_post = models.ForeignKey('Posts', models.DO_NOTHING, db_column='FK_Post', primary_key=True)  # Field name made lowercase.
    link = models.CharField(db_column='Link', max_length=2000, blank=True, null=True)  # Field name made lowercase.
    yes = models.IntegerField(db_column='Yes', blank=True, null=True)  # Field name made lowercase.
    no = models.IntegerField(db_column='No', blank=True, null=True)  # Field name made lowercase.
    unknown = models.IntegerField(db_column='Unknown', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'lawprojects'


class Pointspost(models.Model):
    fk_post = models.ForeignKey('Posts', models.DO_NOTHING, db_column='FK_Post', blank=True, null=True)  # Field name made lowercase.
    fk_user = models.ForeignKey('Users', models.DO_NOTHING, db_column='FK_User', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'pointspost'


class Posts(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    title = models.CharField(db_column='Title', max_length=50, blank=True, null=True)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=200, blank=True, null=True)  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=5000, blank=True, null=True)  # Field name made lowercase.
    views = models.IntegerField(db_column='Views', blank=True, null=True)  # Field name made lowercase.
    date = models.DateField(db_column='Date', blank=True, null=True)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=20, blank=True, null=True)  # Field name made lowercase.
    fk_user = models.ForeignKey('Users', models.DO_NOTHING, db_column='FK_User', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'posts'


class Profilepictures(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    path = models.CharField(db_column='Path', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'profilepictures'


class Stadistics(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    yes = models.IntegerField(db_column='Yes', blank=True, null=True)  # Field name made lowercase.
    no = models.IntegerField(db_column='No', blank=True, null=True)  # Field name made lowercase.
    unknown = models.IntegerField(db_column='Unknown', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'stadistics'


class Tags(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    tag = models.CharField(db_column='Tag', max_length=20, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tags'


class Tagsxpost(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    fk_post = models.ForeignKey(Posts, models.DO_NOTHING, db_column='FK_Post', blank=True, null=True)  # Field name made lowercase.
    fk_tag = models.ForeignKey(Tags, models.DO_NOTHING, db_column='FK_Tag', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tagsxpost'


class Users(models.Model):

eGov/personal/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.db import connection
from django.core.urlresolvers import reverse

from smtplib import SMTP
#import smtplib

def contact(request):
    return render(request, 'personal/contact.html')

def nosotros(request):
    return render(request, 'personal/nosotros.html')



def enviarCorreo(request):

    template = loader.get_template('personal/contact.html')
    
    nombre = request.POST.get('nombre')
    apellido = request.POST.get('apellido')
    email = request.POST.get('email')
    telefono = request.POST.get('telefono')
    mensaje = request.POST.get('mensaje')
    passwordE = request.POST.get('password')

    mensajeE = ''
    mensajeE += 'Nombre: ' + nombre + '\n'
    mensajeE += 'Apellido: ' + apellido + '\n'
    mensajeE += 'Telefono: ' + telefono + '\n'
    mensajeE += mensaje + '\n'
    
    destino = "egov881@gmail.com"
    asunto = "necesito contactar"

    EnviarCorreo = SMTP()
    EnviarCorreo.connect("smtp.gmail.com", 587)
    EnviarCorreo.starttls()
    EnviarCorreo.ehlo()
    EnviarCorreo.login(email, passwordE)

    Cabecera = 'To:' + destino + '\n'     
    Cabecera += 'From: ' + email + '\n'
    Cabecera += 'Subject: ' + asunto + '\n'+'\n'

    EnviarCorreo.sendmail(email, destino, Cabecera + mensajeE)

    EnviarCorreo.close()
    
 

    return HttpResponseRedirect(reverse('personal:contact'))
    
    
    

eGov/personal/templates/personal/contact.html
{% extends "home/header.html" %}



{% block content %}
<br>
<br>
<div class="container">

    <form class="well form-horizontal" method='POST' action='{% url 'personal:enviarCorreo' %}'  > {% csrf_token %} 
<fieldset>

<!-- Form Name -->
<legend>Contatecnos</legend>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-2 control-label">Nombre</label>  
  <div class="col-md-6 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon" id="sizing-addon1"><i class="glyphicon glyphicon-user"></i></span>
  <input  required name="nombre" placeholder="Nombre" class="form-control"  type="text">
    </div>
  
</div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-2 control-label" >Apellido</label> 
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input required name="apellido" placeholder="Apellido" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-2 control-label">Email</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <input required name="email" placeholder="Email" class="form-control"  type="text">
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-2 control-label">Contraseña</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <input required name="password" placeholder="Contraseña" class="form-control"  type="password">
    </div>
  </div>
</div>


<!-- Text input-->
       
<div class="form-group">
  <label class="col-md-2 control-label">Telefono</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
  <input required name="telefono" placeholder="Telefono" class="form-control" type="text">
    </div>
  </div>
</div>






  
<div class="form-group">
  <label class="col-md-2 control-label">Mensaje</label>
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
        	<textarea class="form-control" required name="mensaje" placeholder="Escriba su mensaje" rows="5"></textarea>
  </div>
  </div>
</div>

<
<!-- Button -->
<div class="form-group">
  <label class="col-md-2 control-label"></label>
  <div class="col-md-7" align="right">
    <button type="submit" class="btn btn-danger" >Enviar <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
</form>
</div>
    </div><!-- /.container -->


{% endblock %}

eGov/personal/templates/personal/nosotros.html
{% extends "home/header.html" %}

{% block content %}
<h3>Somos una compañía comprometida con el conocimiento general sobre procesos democráticos en Costa Rica</h3>
<h3>Nos contactamos con equipos excelentes que sean capaces de realizar proyectos que resulten en productos de calidad</h3>
<h3>Hemos estado brindando aplicaciones a través de los años</h3>
<h3>Para más información: </h3>
<h3>Correo electrónico: egov881@gmail.com</h3>
<h3>Teléfono: 27719090</h3>

{% endblock %}