eGov/blog/urls.py
from django.conf.urls import url, include
from . import views
from django.views.generic import ListView, DetailView
from blog.models import Posts

urlpatterns = [ 
                url(r'^noticias/$', views.Noticias, name='noticias'),

                url(r'^insertPost/$', views.insertPost, name='insertPost'),

                url(r'^insertProject/$', views.insertProject, name='insertProject'),

                url(r'^updateUser/$', views.updateUser, name='updateUser'),

                url(r'^proyectos/$', views.Proyectos, name='proyectos'),

                url(r'^noticias/(?P<id>[0-9]+)$',views.NoticiasDetail, name='postNoticias'),

            

                url(r'^noticias/aceptarNoticia/(?P<id>[0-9]+)$',views.aceptarNoticia, name='aceptarNoticia'),

                url(r'^noticias/rechazarNoticia/(?P<id>[0-9]+)$',views.rechazarNoticia, name='rechazarNoticia'),

                url(r'^proyectos/addYes/(?P<id>[0-9]+)/$', views.ProyectoAddYes, name='ProyectoAddYes'),

                url(r'^proyectos/addNo/(?P<id>[0-9]+)/$', views.ProyectoAddNo, name='ProyectoAddNo'),

                url(r'^proyectos/addUnknown/(?P<id>[0-9]+)/$', views.ProyectoAddUnknown, name='ProyectoAddUnknown'),

                url(r'^noticias/deletePost/(?P<id>[0-9]+)$',views.deletePost, name='deletePost'),

                url(r'^proyectos/(?P<id>[0-9]+)/$', views.ProyectosDetail, name='postProyectos'),
                
                url(r'^proyectos/new/$', views.newProject, name='newProject'),

                url(r'^noticias/new/$', views.newNoticia, name='newNoticia'),

                url(r'^noticias/editar/(?P<id>[0-9]+)$', views.editarNoticia, name='editarNoticia'),

                url(r'^noticias/editarEsp/(?P<id>[0-9]+)$', views.editarNoticiaEsp, name='editarNoticiaEsp'),

                url(r'^perfil/$', views.Profile, name='Perfil'),

                url(r'^comentario/(?P<id>[0-9]+)$',views.insertComment, name='insertComment'),
				
				url(r'^comentarioProyecto/(?P<id>[0-9]+)$',views.insertCommentProject, name='insertCommentProject'),


                
            ]

eGov/eGov/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace="home")),
    url(r'^personal/', include('personal.urls', namespace="personal")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^blogClient/', include('blogClient.urls', namespace="blogClient")),
    
]

eGov/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^errorLogin/$', views.errorLogin, name='errorLogin'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^login/redirectNoticias$', views.redirectNoticias, name='redirectNoticias'),
    url(r'^login/redirectProyectos$', views.redirectProyectos, name='redirectProyectos'),
    url(r'^login/redirectPerfil$', views.redirectPerfil, name='redirectPerfil'),
    url(r'^salir$', views.salir, name='salir'),
    ]

eGov/home/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class BlogComment(models.Model):
    user = models.CharField(max_length=140)
    date = models.DateTimeField()
    description = models.TextField()
    post = models.ForeignKey('BlogPost', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'blog_comment'


class BlogPost(models.Model):
    title = models.CharField(max_length=140)
    description = models.TextField()
    content = models.TextField()
    date = models.DateTimeField()
    user = models.CharField(max_length=140)
    userp = models.ForeignKey('BlogUser', models.DO_NOTHING, db_column='userP_id', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'blog_post'


class BlogUser(models.Model):
    name = models.CharField(max_length=140)
    lastname = models.CharField(db_column='lastName', max_length=140)  # Field name made lowercase.
    email = models.CharField(max_length=140)
    password = models.CharField(max_length=140)

    class Meta:
        managed = False
        db_table = 'blog_user'


class Comments(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=500, blank=True, null=True)  # Field name made lowercase.
    date = models.DateField(db_column='Date', blank=True, null=True)  # Field name made lowercase.
    fk_user = models.ForeignKey('Users', models.DO_NOTHING, db_column='FK_User', blank=True, null=True)  # Field name made lowercase.
    fk_post = models.ForeignKey('Posts', models.DO_NOTHING, db_column='FK_Post', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'comments'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Images(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    path = models.CharField(db_column='Path', max_length=100, blank=True, null=True)  # Field name made lowercase.
    fk_post = models.ForeignKey('Posts', models.DO_NOTHING, db_column='FK_Post', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'images'


class Lawprojects(models.Model):
    fk_post = models.ForeignKey('Posts', models.DO_NOTHING, db_column='FK_Post', primary_key=True)  # Field name made lowercase.
    link = models.CharField(db_column='Link', max_length=2000, blank=True, null=True)  # Field name made lowercase.
    yes = models.IntegerField(db_column='Yes', blank=True, null=True)  # Field name made lowercase.
    no = models.IntegerField(db_column='No', blank=True, null=True)  # Field name made lowercase.
    unknown = models.IntegerField(db_column='Unknown', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'lawprojects'


class Pointspost(models.Model):
    fk_post = models.ForeignKey('Posts', models.DO_NOTHING, db_column='FK_Post', blank=True, null=True)  # Field name made lowercase.
    fk_user = models.ForeignKey('Users', models.DO_NOTHING, db_column='FK_User', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'pointspost'


class Posts(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    title = models.CharField(db_column='Title', max_length=50, blank=True, null=True)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=200, blank=True, null=True)  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=5000, blank=True, null=True)  # Field name made lowercase.
    views = models.IntegerField(db_column='Views', blank=True, null=True)  # Field name made lowercase.
    date = models.DateField(db_column='Date', blank=True, null=True)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=20, blank=True, null=True)  # Field name made lowercase.
    fk_user = models.ForeignKey('Users', models.DO_NOTHING, db_column='FK_User', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'posts'


class Profilepictures(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    path = models.CharField(db_column='Path', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'profilepictures'


class Stadistics(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    yes = models.IntegerField(db_column='Yes', blank=True, null=True)  # Field name made lowercase.
    no = models.IntegerField(db_column='No', blank=True, null=True)  # Field name made lowercase.
    unknown = models.IntegerField(db_column='Unknown', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'stadistics'


class Tags(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    tag = models.CharField(db_column='Tag', max_length=20, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tags'


class Tagsxpost(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    fk_post = models.ForeignKey(Posts, models.DO_NOTHING, db_column='FK_Post', blank=True, null=True)  # Field name made lowercase.
    fk_tag = models.ForeignKey(Tags, models.DO_NOTHING, db_column='FK_Tag', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tagsxpost'


class Users(models.Model):

eGov/home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Comments, Posts
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.db import connection
from django.core.urlresolvers import reverse

import random

def index(request):
    
    template = loader.get_template('home/inicio.html')
    context = {}
    

    return HttpResponse(template.render(context, request))


def errorLogin(request):
    template = loader.get_template('home/inicio.html')
    context = {
        'error': "El usuario o contraseña es incorrecto"
        }
    

    return HttpResponse(template.render(context, request))

def login(request):

    template = loader.get_template('home/header.html')
    context = {}
    
    username = request.POST.get('username')
    password = str(request.POST.get('password'))
    cur = connection.cursor()
    login = cur.callproc('login', [username, password])
    login = cur.fetchall()
    cur.close
    if login == ():
        return HttpResponseRedirect(reverse('home:errorLogin'))
    else:
        request.session['Usuario'] = login[0][0]
        request.session['TipoUsuario'] = login[0][1]
        request.session['IdTipoUsuario'] = login[0][2]
        
        if login[0][1] == "Administrador":
            return HttpResponseRedirect(reverse('blog:noticias'))
        elif login[0][1] == "Cliente":
            return HttpResponseRedirect(reverse('blogClient:noticias'))

def signin(request):
    
    template = loader.get_template('home/header.html')
    context = {}
    
    name = request.POST.get('name')
    lastname = str(request.POST.get('lastname'))
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = str(request.POST.get('password'))
    path = random.randrange(101)
    cur = connection.cursor()
    cur.callproc('SignIn', [name, lastname, username, email, password,path])
    cur.fetchall()
    cur.nextset()

    
    login = cur.callproc('login', [username, password])
    login = cur.fetchall()
    cur.close
   
    request.session['Usuario'] = login[0][0]
    request.session['TipoUsuario'] = login[0][1]
    request.session['IdTipoUsuario'] = login[0][2]
    
    return HttpResponseRedirect(reverse('blogClient:noticias'))
    

    
    
def redirectNoticias(request):
    
    template = loader.get_template('home/header.html')
    
    if request.session['TipoUsuario'] == "Administrador":
        return HttpResponseRedirect(reverse('blog:noticias'))

    elif request.session['TipoUsuario'] == "Cliente":
        return HttpResponseRedirect(reverse('blogClient:noticias'))

def redirectProyectos(request):
    
    template = loader.get_template('home/header.html')
    
    if request.session['TipoUsuario'] == "Administrador":
        return HttpResponseRedirect(reverse('blog:proyectos'))

    elif request.session['TipoUsuario'] == "Cliente":
        return HttpResponseRedirect(reverse('blogClient:proyectos'))

def redirectPerfil(request):
    
    template = loader.get_template('home/header.html')
    
    print(request.session['TipoUsuario'])
    if request.session['TipoUsuario'] == "Administrador":
        return HttpResponseRedirect(reverse('blog:Perfil'))

    elif request.session['TipoUsuario'] == "Cliente":
        print("Entra a blogclient")
        return HttpResponseRedirect(reverse('blogClient:Perfil'))
    
    
def salir(request):

    template = loader.get_template('home/header.html')
    
    del request.session['Usuario']
    del request.session['TipoUsuario']
    del request.session['IdTipoUsuario']

    request.session.modified = True

    return HttpResponseRedirect(reverse('personal:contact'))

eGov/home/templates/home/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>eGov</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}" type = "text/css"/>
	<script src="{%static 'home/js/jquery.min.js' %}"></script>
	<script src="{%static 'home/js/bootstrap.min.js' %}"></script>
	
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	
	<style type="text/css">
		html,
		body {
		  height:100%
		}
		
		body { padding-top: 50px; }
	</style>
	
	<style>.carousel-inner > .item > img { width:100%; height:550px; } </style>
	
</head>

<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid" >
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">
		<img alt="Brand" src="{% static 'home/img/eGovLogo.png' %}" style='max-height:50px;'>
	  </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      
	  {% if not request.session.Usuario %}
		  <ul class="nav navbar-nav navbar-right">
				<li><a  href="#" data-toggle="modal" data-target="#SignUp"><span class="glyphicon glyphicon-user"></span> Registrarse</a></li>
				<li><a href="#" data-toggle="modal" data-target="#Login"><span class="glyphicon glyphicon-log-in"></span> Ingresar</a></li>
		  </ul>
	  {% endif %}
	  
	  {% if request.session.Usuario %}
			<ul class="nav navbar-nav">
				<li class="active"><a href="/">Inicio</a></li>
				<li><a href='/login/redirectNoticias'>Noticias</a></li>
				<li><a href='/login/redirectProyectos'>Proyectos</a></li>
				<li><a href='/personal/nosotros'>Sobre nosotros</a></li>
				<li><a href='/personal/contacto'>Contacto</a></li>
				<li><a href='/login/redirectPerfil'>Perfil</a></li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li><a href="/salir" data-toggle="modal" data-target="#Login"><span class="glyphicon glyphicon-log-in"></span> Salir</a></li>
			</ul>
	  {% endif %}
	  
    </div>
	
	{% if error %}
		<h3>{{error}}</h3>
	{% endif %}
  
</nav>
  <!-- Modal SignUp -->
<div class="modal fade" id="SignUp" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
	  <div class="modal-content">
      <div class="modal-header">
        				<button type="button" class="close" data-dismiss="modal">
        					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        				</button>
        				<h3 class="modal-title" id="modal-register-label">Registrarse</h3>
        				<p>Escribe tu informaicon en los espacios para crear un usuario</p>
        			</div>
        			
        			<div class="modal-body">
        				
	                    <form role="form" class="registration-form" method='POST' action='{% url 'home:signin' %}'  > {% csrf_token %}
	                    	<div class="form-group">
	                    		<label class="sr-only" for="form-first-name">Nombre</label>
	                        	<input type="text" required name='name' placeholder="First name..." class="form-first-name form-control" id="form-first-name">
	                        </div>
	                        <div class="form-group">
	                        	<label class="sr-only" for="form-last-name">Apellido</label>
	                        	<input type="text" required name='lastname' placeholder="Last name..." class="form-last-name form-control" id="form-last-name">
	                        </div>
							<div class="form-group">
	                        	<label class="sr-only" for="form-username">Nombre de usuario</label>
	                        	<input type="text" required name='username' placeholder="Nombre de usuario..." class="form-username form-control" id="form-username">
	                        </div>
	                        <div class="form-group">
	                        	<label class="sr-only" for="form-email">Correo</label>
	                        	<input type="text" required name='email' placeholder="Email..." class="form-email form-control" id="form-email">
	                        </div>
	                        <div class="form-group">
	                        	<label class="sr-only" for="form-about-yourself">Contraseña</label>
	                        	<input type="password" required name='password' placeholder="Contraseña..." class="form-password form-control" id="form-password">
	                        </div>
	                        <button type="submit" class="btnIngresar">Registrarse</button>
	                    </form>
	                    
        			</div>
				</div>
      
    </div>
  </div>
  
    <!-- Modal Login -->
<div class="modal fade" id="Login" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
        				<button type="button" class="close" data-dismiss="modal">
        					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        				</button>
        				<h3 class="modal-title" id="modal-login-label">Ingresar</h3>
        				<p>Escribe tu usuario y contraseña para ingresar</p>
        			</div>
        			
        			<div class="modal-body">
        				
	                    <form role="form" class="login-form" method='POST' action='{% url 'home:login' %}'  > {% csrf_token %} 
	                    	<div class="form-group">
	                    		<label class="sr-only" for="form-username">Usuario</label>
	                        	<input type="text" required name='username' placeholder="Usuario..." class="form-username form-control" id="form-username">
	                        </div>
	                        <div class="form-group">
	                        	<label class="sr-only" for="form-password">Contraseña</label>
	                        	<input type="password" required name='password' placeholder="Contraseña..." class="form-password form-control" id="form-password">
	                        </div>
	                        <button type="submit"class="btnIngresar">Ingresar</button>
	                    </form>
	                    
        			</div>
        			
      </div>
      
    </div>
  </div>
	
  </div>
		
		  <div>
			   {% block content %}
			   {% endblock %}	
			</div>
		

	<footer>
		<div class="container-fluid" style='margin-left:15px;padding-top:8px'>
			<p><a href="#" target="blank">Contacto</a> | <a href="#" target="blank">LinkedIn</a> | <a href="#" target="blank">Twitter</a> | <a href="#" target="blank">Google+</a></p>
		</div>
	</footer>	
	
</body>

</html>

eGov/home/templates/home/inicio.html
{% extends "home/header.html" %}
{% block content %}
{% load staticfiles %}
<div class='container-fluid'>
<div id="myCarousel" class="carousel slide" data-ride="carousel" >
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <img src="{% static 'home/img/image1.jpg' %}" alt="Teatro Costa Rica" style="width:100%;" >
        <div class="carousel-caption">
          <h3>Teatro Melico Salazar</h3>
        </div>
      </div>

      <div class="item">
        <img src="{% static 'home/img/image2.jpg' %}" alt="Hotel Marriott" style="width:100%;"  >
        <div class="carousel-caption">
          <h3>Hotel Marriott</h3>
        </div>
      </div>
    
      <div class="item">
        <img src="{% static 'home/img/image3.jpg' %}" alt="San Jose" style="width:100%;">
        <div class="carousel-caption">
          <h3>San Jose</h3>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</div>

{% endblock %}