eGov/blog/urls.py
from django.conf.urls import url, include
from . import views
from django.views.generic import ListView, DetailView
from blog.models import Posts

urlpatterns = [ 
                url(r'^noticias/$', views.Noticias, name='noticias'),

                url(r'^insertPost/$', views.insertPost, name='insertPost'),

                url(r'^insertProject/$', views.insertProject, name='insertProject'),

                url(r'^updateUser/$', views.updateUser, name='updateUser'),

                url(r'^proyectos/$', views.Proyectos, name='proyectos'),

                url(r'^noticias/(?P<id>[0-9]+)$',views.NoticiasDetail, name='postNoticias'),

            

                url(r'^noticias/aceptarNoticia/(?P<id>[0-9]+)$',views.aceptarNoticia, name='aceptarNoticia'),

                url(r'^noticias/rechazarNoticia/(?P<id>[0-9]+)$',views.rechazarNoticia, name='rechazarNoticia'),

                url(r'^proyectos/addYes/(?P<id>[0-9]+)/$', views.ProyectoAddYes, name='ProyectoAddYes'),

                url(r'^proyectos/addNo/(?P<id>[0-9]+)/$', views.ProyectoAddNo, name='ProyectoAddNo'),

                url(r'^proyectos/addUnknown/(?P<id>[0-9]+)/$', views.ProyectoAddUnknown, name='ProyectoAddUnknown'),

                url(r'^noticias/deletePost/(?P<id>[0-9]+)$',views.deletePost, name='deletePost'),

                url(r'^proyectos/(?P<id>[0-9]+)/$', views.ProyectosDetail, name='postProyectos'),
                
                url(r'^proyectos/new/$', views.newProject, name='newProject'),

                url(r'^noticias/new/$', views.newNoticia, name='newNoticia'),

                url(r'^noticias/editar/(?P<id>[0-9]+)$', views.editarNoticia, name='editarNoticia'),

                url(r'^noticias/editarEsp/(?P<id>[0-9]+)$', views.editarNoticiaEsp, name='editarNoticiaEsp'),

                url(r'^perfil/$', views.Profile, name='Perfil'),

                url(r'^comentario/(?P<id>[0-9]+)$',views.insertComment, name='insertComment'),
				
				url(r'^comentarioProyecto/(?P<id>[0-9]+)$',views.insertCommentProject, name='insertCommentProject'),


                
            ]

eGov/eGov/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace="home")),
    url(r'^personal/', include('personal.urls', namespace="personal")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^blogClient/', include('blogClient.urls', namespace="blogClient")),
    
]

eGov/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Comments, Posts
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.db import connection
from django.core.urlresolvers import reverse



def newProject(request):
    return render(request, 'blog/newProyecto.html')

def newNoticia(request):
    return render(request, 'blog/newNoticia.html')

def Profile(request):
    user = int(request.session['Usuario'])
    
    cur = connection.cursor()
    cur.callproc('UserData', [user,])
    datos = cur.fetchall()
    print(datos)
    name = datos[0][0]
    lastname = datos[0][1]
    email = datos[0][2]
    path = datos[0][3]
    points = str(datos[0][4])+"%"
    
    

    cur.nextset()
    cur.callproc('PostsXUser', [user,])
    posts = cur.fetchall()
    
    cur.close
    
    print(posts)
    context = {
        'name': name,
        'lastname': lastname,
        'email': email, 
        'posts': posts,
        'path': path,
        'points': points
    }
    template = loader.get_template('blog/profile.html')
    return HttpResponse(template.render(context, request))

template_name = 'blog/postProyectos.html'


def Noticias(request):
    
    template = loader.get_template('blog/noticias.html')

    cur = connection.cursor()
    cur.callproc('selectNewsAdmin', [])
    noticias = cur.fetchall()
    cur.close
    


    print(noticias)
    context = {
    	'noticias': noticias 
    }
    return HttpResponse(template.render(context, request))

def Proyectos(request):
    
    template = loader.get_template('blog/proyectos.html')
	
    cur = connection.cursor()
    cur.callproc('selectLawProjects', [])
    proyectos = cur.fetchall()
    cur.close
    
    
    
    context = {
    	'proyectos': proyectos 
    }
    return HttpResponse(template.render(context, request))



def NoticiasDetail(request, id):
    numComentarios = 0
    resultado = ""
    user = int(request.session['Usuario'])
    post = get_object_or_404(Posts, pk=id)
    cur = connection.cursor()
    cur.callproc('commentsPost', [id,])
    comentarios = cur.fetchall()
        
    
    cur.nextset()
    cur.callproc('numCommentPost', [id,])
    num = cur.fetchall()

    cur.nextset()
    cur.callproc('addViewPost', [id,])

    cur.nextset()
    cur.callproc('getPointPost', [user, id,])
    points = cur.fetchall()


    cur.nextset()
    cur.callproc('getUserPost', [id,])
    userElements = cur.fetchall()
    
    cur.close 
    template = loader.get_template('blog/PostNoticias.html')
    

    if num != ():
        numComentarios = num[0][1]

    
    if user != userElements[0][0]:
        resultado = "Mostrar"

    print(comentarios)
    context = {
    'post': post,
    'comentarios': comentarios,
    'id': id,
    'numComentarios': numComentarios,
    'resultado': resultado,
    'userElements': userElements[0],
    }
    return HttpResponse(template.render(context, request))

def ProyectosDetail(request, id):
    numComentarios = 0
    
    resultado = ""
    user = int(request.session['Usuario'])
    
    post = get_object_or_404(Posts, pk=id)
    template = loader.get_template('blog/PostProyectos.html')
    

    cur = connection.cursor()
    cur.callproc('commentsPost', [id,])
    comentarios = cur.fetchall()
    
    cur.nextset()

    cur.callproc('getLinkLawProject', [id,])
    link = cur.fetchall()

    print(link)

    cur.nextset()

    
    cur.callproc('numCommentPost', [id,])
    num = cur.fetchall()
    
    cur.nextset()
    cur.callproc('addViewPost', [id,])

    cur.nextset()
    cur.callproc('getStadisticsProject', [id,])
    estadisticas = cur.fetchall()

    cur.nextset()
    cur.callproc('getVotePost', [user, id,])
    votes = cur.fetchall()

    cur.nextset()
    cur.callproc('getUserPost', [id,])
    userElements = cur.fetchall()

    print("POST")
    
    if votes != ():
        resultado = "Mostrar"

    if num != ():
        numComentarios = num[0][1]

    linkE = ""

    if link != ():
        linkE = link[0][0]


    Path = ""
    if comentarios != ():
        
        Path = comentarios[0][3]

    context = {
    'post': post,
    'comentarios': comentarios,
    'id': id,
    'numComentarios': numComentarios,
    'estadisticas': estadisticas[0],
    'resultado': resultado,
    'Path': Path,
    'userElements': userElements[0],
    'linkE':linkE
    }
    return HttpResponse(template.render(context, request))


def insertComment(request, id):

    template = loader.get_template('blog/PostNoticias.html')
    comment = request.POST.get('comment')
    cur = connection.cursor()
    user = int(request.session['Usuario'])
    cur.callproc('EGSP_InsertComment', [comment, user, id,])
    cur.close
    context = {}
	 
    return HttpResponseRedirect(reverse('blog:postNoticias', args=[id])) 
	
def insertCommentProject(request, id):

    template = loader.get_template('blog/PostNoticias.html')
    comment = request.POST.get('comment')
    cur = connection.cursor()
    user = int(request.session['Usuario'])
    cur.callproc('EGSP_InsertComment', [comment, user, id,])
    cur.close
    context = {}
	 
    return HttpResponseRedirect(reverse('blog:postProyectos', args=[id])) 
    

def insertPost(request):
    template = loader.get_template('blog/newNoticia.html')
    title = request.POST.get('title')
    comment = request.POST.get('comment')
    content = request.POST.get('content')
    user = int(request.session['Usuario'])
    cur = connection.cursor()
    cur.callproc('EInsertPostAdmin', [title, comment, content, user])
    cur.close
    return HttpResponseRedirect(reverse('blog:noticias')) 


def insertProject(request):
    template = loader.get_template('blog/newNoticia.html')
    title = request.POST.get('title')
    comment = request.POST.get('comment')
    content = request.POST.get('content')
    link = request.POST.get('link')

    user = int(request.session['Usuario'])
    
    cur = connection.cursor()
    cur.callproc('EInsertPostAdmin', [title, comment, content, user])
    
    cur.nextset()
    
    cur.callproc('selectLastPost', [])
    Post = cur.fetchall()
    idPost = int(Post[0][0])
    
    cur.nextset()

    cur.callproc('EInsertLawProject', [idPost, link])
    
    cur.close

    
    return HttpResponseRedirect(reverse('blog:noticias')) 
    
def updateUser(request):
    template = loader.get_template('blog/profile.html')
    
    user = int(request.session['Usuario'])
    idTipoUsuario = int(request.session['IdTipoUsuario'])

    username = request.POST.get('username')
    lastname = request.POST.get('lastname')
    email =  request.POST.get('email')
    password = request.POST.get('password')

    cur = connection.cursor()
    cur.callproc('EGSP_UpdateUser', [user, username, lastname, email, password, idTipoUsuario])
    cur.close

    return HttpResponseRedirect(reverse('blog:Perfil'))

def editarNoticia(request, id):
    
    template = loader.get_template('blog/editarNoticia.html')
    context = {
        'id': id
    }
    return HttpResponse(template.render(context, request))


def editarNoticiaEsp(request, id):

    template = loader.get_template('blog/editarNoticia.html')
    title = request.POST.get('title')
    comment = request.POST.get('description')
    content = request.POST.get('content')

    cur = connection.cursor()
    cur.callproc('updatePost', [id, title, comment, content])
    cur.close
    return HttpResponseRedirect(reverse('blog:Perfil'))


def deletePost(request, id):

    template = loader.get_template('blog/profile.html')
    context = {}
    cur = connection.cursor()
    cur.callproc('deletePost', [id])
    cur.close

    return HttpResponseRedirect(reverse('blog:Perfil'))


def ProyectoAddYes(request, id):
    
    user = int(request.session['Usuario'])
    
    cur = connection.cursor()
    cur.callproc('addYesProject', [id])

    cur.nextset()
    cur.callproc('InsertVotePost', [user, id,])

    cur.close


    return HttpResponseRedirect(reverse('blog:postProyectos', args=[id])) 
    

def ProyectoAddNo(request, id):
    
    user = int(request.session['Usuario'])
    

    cur = connection.cursor()
    cur.callproc('addNoProject', [id])

    cur.nextset()
    cur.callproc('InsertVotePost', [user, id,])

    cur.close

    return HttpResponseRedirect(reverse('blog:postProyectos', args=[id])) 
    

def ProyectoAddUnknown(request, id):
    
    user = int(request.session['Usuario'])
    
    
    cur = connection.cursor()
    cur.callproc('addUnknownProject', [id])

    cur.nextset()
    cur.callproc('InsertVotePost', [user, id,])

    cur.close

    return HttpResponseRedirect(reverse('blog:postProyectos', args=[id])) 


def aceptarNoticia(request, id):

    cur = connection.cursor()
    cur.callproc('acceptNew', [id])
    cur.close

    return HttpResponseRedirect(reverse('blog:noticias'))

def rechazarNoticia(request, id):

    cur = connection.cursor()
    cur.callproc('rejectNew', [id])
    cur.close

    return HttpResponseRedirect(reverse('blog:noticias'))

eGov/blog/templates/blog/editarNoticia.html
{% extends "home/header.html" %}

{% block content %}

<br>
<br>
<div class="container">

    <form class="well form-horizontal" method='POST' action='{% url 'blog:editarNoticiaEsp' id %}'  > {% csrf_token %} 
	
	
<fieldset>

<!-- Form Name -->

	<!-- Text input-->

	<div class="form-group">
	  <label class="col-md-2 control-label">Titulo</label>  
	  <div class="col-md-6 inputGroupContainer">
	  <div class="input-group">
	  <span class="input-group-addon" id="sizing-addon1"><i class="glyphicon glyphicon-tags"></i></span>
	  <input  required name='title' placeholder="Nombre" class="form-control"  type="text">
		</div>
	  
	</div>
	</div>







	  
	<div class="form-group">
	  <label class="col-md-2 control-label">Descripcion</label>
		<div class="col-md-6 inputGroupContainer">
		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				<textarea class="form-control" required name='description' placeholder="Escriba su mensaje" rows="10"></textarea>
	  </div>
	  </div>
	</div>
	
	<div class="form-group">
	  <label class="col-md-2 control-label">Contenido</label>
		<div class="col-md-6 inputGroupContainer">
		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				<textarea class="form-control" required name='content' placeholder="Escriba su mensaje" rows="10"></textarea>
	  </div>
	  </div>
	</div>

	

	<!-- Button -->

	<div class="form-group">
	  <label class="col-md-2 control-label"></label>
	  <div class="col-md-7" align="right">
		<button type="submit" class="btn btn-danger" >Editar <span class="glyphicon glyphicon-send"></span></button>
	  </div>
	</div>

</fieldset>
</form>
</div>
	</div><!-- /.container -->

{% endblock %}

eGov/blog/templates/blog/newNoticia.html
{% extends "home/header.html" %}

{% block content %}

<br>
<br>
<div class="container">

    <form class="well form-horizontal" method='POST' action='{% url 'blog:insertPost'  %}'  > {% csrf_token %}
<fieldset>

<!-- Form Name -->

	<!-- Text input-->

	<div class="form-group">
	  <label class="col-md-2 control-label">Titulo</label>  
	  <div class="col-md-6 inputGroupContainer">
	  <div class="input-group">
	  <span class="input-group-addon" id="sizing-addon1"><i class="glyphicon glyphicon-tags"></i></span>
	  <input  required name='title' placeholder="Nombre" class="form-control"  type="text">
		</div>
	  
	</div>
	</div>







	  
	<div class="form-group">
	  <label class="col-md-2 control-label">Descripcion</label>
		<div class="col-md-6 inputGroupContainer">
		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				<textarea class="form-control" required name='comment' placeholder="Escriba su mensaje" rows="10"></textarea>
	  </div>
	  </div>
	</div>
	
	<div class="form-group">
	  <label class="col-md-2 control-label">Contenido</label>
		<div class="col-md-6 inputGroupContainer">
		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				<textarea class="form-control" required name='content' placeholder="Escriba su mensaje" rows="10"></textarea>
	  </div>
	  </div>
	</div>

	<
	<!-- Button -->

	<div class="form-group">
	  <label class="col-md-2 control-label"></label>
	  <div class="col-md-7" align="right">
		<button type="submit" class="btn btn-danger" >Publicar <span class="glyphicon glyphicon-send"></span></button>
	  </div>
	</div>

</fieldset>
</form>
</div>
	</div><!-- /.container -->

{% endblock %}

eGov/blog/templates/blog/newProyecto.html
{% extends "home/header.html" %}

{% block content %}

<br>
<br>
<div class="container">

    <form class="well form-horizontal" id="contact_form" method='POST' action='{% url 'blog:insertProject'  %}'  > {% csrf_token %}
<fieldset>

<!-- Form Name -->
<legend>Nueva Noticia</legend>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-2 control-label">Titulo</label>  
  <div class="col-md-6 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon" id="sizing-addon1"><i class="glyphicon glyphicon-tags"></i></span>
  <input  required name="title" placeholder="Nombre" class="form-control"  type="text">
    </div>
  
</div>
</div>







  
<div class="form-group">
  <label class="col-md-2 control-label">Descripcion</label>
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
        	<textarea class="form-control" required name="comment" placeholder="Escriba su mensaje" rows="10"></textarea>
  </div>
  </div>
</div>

<div class="form-group">
	  <label class="col-md-2 control-label">Contenido</label>
		<div class="col-md-6 inputGroupContainer">
		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				<textarea class="form-control" required name='content' placeholder="Escriba su mensaje" rows="10"></textarea>
	  </div>
	  </div>
	</div>

<div class="form-group">
  <label class="col-md-2 control-label">URL</label>  
  <div class="col-md-6 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon" id="sizing-addon1">@</span>
  <input  required name="link" placeholder="URL" class="form-control"  type="text">
    </div>
  
</div>
</div>

<
<!-- Button -->
<div class="form-group">
  <label class="col-md-2 control-label"></label>
  <div class="col-md-7" align="right">
    <button type="submit" class="btn btn-danger" >Publicar <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
</form>
</div>
    </div><!-- /.container -->
{% endblock %}

eGov/blog/templates/blog/noticias.html
{% extends "home/header.html" %}

{% block content %}

<div class="container">
{% for post in noticias %}

		<h2><a href="/blog/noticias/{{post.4}}">  {{ post.0 }}</a></h2>
		<h4>{{ post.3|date:"Y-m-d" }}</h4>
		<p>{{post.1}}</p>
		
	{% endfor %}
	
	
	
	
		 
	<div align="right" >
		<a href="/blog/noticias/new/"><button type="submit" class="btn btn-danger" style="margin-top:20px;">Nueva Noticia</button></a>
	</div>
		  
	
	
	
</div>
{% endblock %}

eGov/blog/templates/blog/postNoticias.html
{% extends "home/header.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">

<h3>{{ post.title }}</h3>
<h6> on {{ post.date }}</h6>

<div class = "container">
	{{ post.content|safe|linebreaks}}
	
	<h5> Autor: {{ userElements.3 }}</h5>
	<h5> Puntaje del autor: {{ userElements.2 }}</h5>
</div>
	<br><br>
	
	{% if resultado == "Mostrar" %}
	
	<div align="right">
			    <a href="/blog/noticias/aceptarNoticia/{{id}}" <button type="submit" class="btn btn-danger">Aceptar</button></a>
	</div>
	
	<div align="right">
			    <a href="/blog/noticias/rechazarNoticia/{{id}}" <button type="submit" class="btn btn-danger">Rechazar</button></a>
	</div>
	
	{% endif %}
	
	<h4>Deja un comentario</h4>
      <form method='POST' action='{% url 'blog:insertComment' id %}'  > {% csrf_token %} 
        <div class="form-group">
          <textarea class="form-control" rows="3" required name='comment'></textarea>
        </div>
		<div align="right">
			    <button type="submit" class="btn btn-danger">Enviar</button>
		</div>
      </form>
	  
	  
	
	<p><span class="badge">{{numComentarios}}</span> Comentarios:</p><br>
	<div class="row">
	{% for comment in comentarios %}
	
	      
        <div class="col-sm-2 text-center">
          <img src="{% static comment.3 %}" class="img-circle" height="65" width="65" alt="Avatar">
        </div>
        <div class="col-sm-10">
          <h4>{{comment.1 }}   <small>{{comment.2}}</small></h4>
          <p>{{comment.0}}</p>
          <br>
        </div>
        
        
      
    
	
	{% endfor %}
	</div>
		 
	
	
	
	
</div>
{% endblock %}

eGov/blog/templates/blog/postProyectos.html
{% extends "home/header.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">
<div class="row">
  <div class="col-md-8">
 

		<h3>{{ post.title }}</h3>
		<h6> on {{ post.date }}</h6>

		
			{{ post.content|safe|linebreaks}}
			{{ linkE|safe|linebreaks}}
		<h5> Autor: {{ userElements.3 }}</h5>
		<h5> Puntaje del autor: {{ userElements.2 }}</h5>
			<br><br>
		{% if resultado != "Mostrar" %}
		<div align="right">
			<a  href="/blog/proyectos/addYes/{{id}}"><span class="glyphicon glyphicon-thumbs-up"></span> Aprueba</a>
			&nbsp&nbsp
			<a href="/blog/proyectos/addUnknown/{{id}}"><span class="glyphicon glyphicon-transfer"></span> Neutral</a>
			&nbsp&nbsp
			<a href="/blog/proyectos/addNo/{{id}}"><span class="glyphicon glyphicon-thumbs-down"></span> Desaprueba</a>
		</div>
		{% endif %}
   
			
	</div>
	<div class="col-md-4" style="padding-top:75px;">
				<div class="progress">
		  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{estadisticas.0}}"
		  aria-valuemin="0" aria-valuemax="100" style="width:{{estadisticas.0}}%">
			{{estadisticas.0}}% Aprueba
		  </div>
		</div>

		<div class="progress">
		  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="{{estadisticas.2}}"
		  aria-valuemin="0" aria-valuemax="100" style="width:{{estadisticas.2}}%">
			{{estadisticas.2}}% Neutral
		  </div>
		</div>

		<div class="progress">
		  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="{{estadisticas.1}}"
		  aria-valuemin="0" aria-valuemax="100" style="width:{{estadisticas.1}}%">
			{{estadisticas.1}}% Desaprueba
		  </div>
		</div>
	 </div>
</div>
	
	<h4>Deja un comentario</h4>
      <form method='POST' action='{% url 'blog:insertCommentProject' id %}'  > {% csrf_token %} 
        <div class="form-group">
          <textarea class="form-control" name='comment' rows="3" required></textarea>
        </div>
		<div align="right">
			    <button type="submit" class="btn btn-danger">Enviar</button>
		</div>
      </form>
	
	<p><span class="badge">{{numComentarios}}</span> Comentarios:</p><br>
	<div class="row">
	{% for comment in comentarios %}
	
	      
        <div class="col-sm-2 text-center">
          <img src="{% static comment.3 %}" class="img-circle" height="65" width="65" alt="Avatar">
        </div>
        <div class="col-sm-10">
          <h4>{{comment.1 }}   <small>{{comment.2}}</small></h4>
          <p>{{comment.0}}</p>
          <br>
        </div>
        
        
      
    
	
	{% endfor %}
	</div>
		 
	
	
	
	
</div>
{% endblock %}

eGov/blog/templates/blog/profile.html
{% extends "home/header.html" %}
{% load staticfiles %}
<style type="text/css">
		.scrollable-menu {
    height: auto;
    max-height: 200px;
    overflow-x: hidden;
}
	</style>

{% block content %}


<div class="container">
<br>
<div class="well well-lg">
<legend>Perfil del usuario</legend>
<div class="row">
  <div class="col-md-4" align= "center">
		<img src="{% static path %}" class="img-circle" height="100" width="100" alt="Avatar">
  </div>
  <div class="col-md-8">
  
  <h3> {{name}} {{lastname}}
  <a href="#" data-toggle="modal" data-target="#editar"><button type="submit" class="btn btn-danger" ><span class="glyphicon glyphicon-pencil"></span></button></h3></a>
  <h4>{{email}}</h4>
	
	<!--  Aca va el nombre y el apellido

<h3>{{ user.name }} {{user.lastname}}</h3>
	<h4>{{ user.email}}</h4>  -->
	
	
  
  </div>
</div>

<br>
<br>

<div class="col-md-4">
<div class="progress">
  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: {{points}}">
    <span class="sr-only">80% Complete (danger)</span> 100 pts
  </div>
</div>
</div>
<br>
<br>



<div class="panel panel-primary">
<div class="panel-heading">
    <h3 class="panel-title">Publicaciones</h3>
  </div>
 
<!-- aqui se hace el for para encontrar las publicacione hechas por el usuario-->

<ul class="list-group">
<div id="list" style="height: auto;
    max-height: 220px;
    overflow-x: hidden;">
    {% for post in posts %}
		
		{% if  post.3  == "Pendiente" %}
			<li class="list-group-item list-group-item-warning">
			
		{% endif %}
		
		{% if  post.3  == "Aceptado" %}
			<li class="list-group-item list-group-item-success">
			
			
		{% endif %}
		
		{% if post.3 == "Rechazado" %}
			<li class="list-group-item list-group-item-danger">
		{% endif %}
		
		
		<div class="row">
	
		<div class="col-md-8">{{post.0}}  </div>
		<div class="col-md-4" align= "right">
		<a href="/blog/proyectos/{{post.2}}" <button type="submit" class="btn btn-primary btn-sm" ><span class="glyphicon glyphicon-eye-open"></span></button></a>
		<a href="/blog/noticias/editar/{{post.2}}"<button type="submit" class="btn btn-info btn-sm" ><span class="glyphicon glyphicon-pencil"></span></button></a>
		<a href="/blog/noticias/deletePost/{{post.2}}" <button type="submit" class="btn btn-danger btn-sm" ><span class="glyphicon glyphicon-remove"></span></button></a>
		</div>
	{% endfor %}
	
	
	</div>
 </ul>



	
</div>

<div class="modal fade" id="editar" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
        				<button type="button" class="close" data-dismiss="modal">
        					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        				</button>
        				<h3 class="modal-title" id="modal-login-label">Editar</h3>
        				<p>Escriba la informacion que desea editar</p>
        			</div>
        			
        			<div class="modal-body">
        				
	                    <form role="form" class="login-form" method='POST' action='{% url 'blog:updateUser'  %}'  > {% csrf_token %}
						<div class="row">
						<div class="col-md-4" align= "center">
							<div class="form-group"> 
	                    		
					  
							
	                        </div>
							 </div>
							
							
							<div class="col-md-8">
	                    	
							
							<div class="form-group"> 
	                    		<label class="sr-only" for="form-username">Usuario</label>
	                        	<input type="text" required name='username' placeholder="Usuario..." class="form-username form-control" id="form-username">
	                        </div>
	                        <div class="form-group">
	                        	<label class="sr-only" for="form-password">Apellido</label>
	                        	<input type="text" required name='lastname' placeholder="Apellido..." class="form-password form-control" id="form-password">
	                        </div>
							<div class="form-group">
	                        	<label class="sr-only" for="form-password">Email</label>
	                        	<input type="text" required name='email' placeholder="Email..." class="form-password form-control" id="form-password">
	                        </div>
							<div class="form-group">
	                        	<label class="sr-only" for="form-password">Contraseña</label>
	                        	<input type="password" required name='password' placeholder="Contraseña..." class="form-password form-control" id="form-password">
	                        </div>
							
							 </div> </div>
							<div align="right">
	                        <button type="submit" class="btn btn-danger" ><span class="glyphicon glyphicon-pencil"></span></button>
							</div>
							
	                    </form>
	                    
        			</div>
        			
      </div>
      
    </div>
  </div>


{% endblock %}

eGov/blog/templates/blog/proyectos.html
{% extends "home/header.html" %}

{% block content %}

<div class="container">
{% for post in proyectos %}

		<h2><a href="/blog/proyectos/{{post.5}}">  {{ post.0 }}</a></h2>
		<h4>{{ post.4|date:"Y-m-d" }}</h4>
		<p>{{post.1}}</p>
		
	{% endfor %}
	
	
		<div align="right" >
		<a href="/blog/proyectos/new/"><button type="submit" class="btn btn-danger" style="margin-top:20px;">Nueva Proyecto</button></a>
	</div>
	
</div>
{% endblock %}